<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Board.AppServices\Board.AppServices.csproj" />
    <ProjectReference Include="..\Board.Infrastructure.DataAccess\Board.Infrastructure.DataAccess.csproj" />
  </ItemGroup>

</Project>
