services:

  board.hosts.api:
    image: board.hosts.api
    build:
      context: .
      dockerfile: src/Hosts/board.Hosts.Api/Dockerfile
    ports:
      - "5001:8080"
    networks:
      - board-network
      
  postgres:
    image: postgres:14
    ports: 
       - "5433:5432"
    environment:     
      POSTGRES_DB: Board
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vgpugdk123098!
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    networks:
      - board-network

  rabbitmq:
    image: rabbitmq:4-management # Use the image with the management plugin
    hostname: my-rabbit # Define a hostname for the RabbitMQ node
    ports:
      - "5672:5672" # Standard AMQP port
      - "15672:15672" # Management UI port
    
    environment:
      RABBITMQ_DEFAULT_USER: guest # Default username (change in production)
      RABBITMQ_DEFAULT_PASS: guest # Default password (change in production)
    networks:
      - board-network

  
  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   networks:
  #     - articles-network



volumes:
  postgres_data: 
  rabbitmq_data:

networks:
  board-network:
  
          